### ISSUE TITLE
Setplayerclass error

### ISSUE THREAD

**Issue by Stinggy** [BlackVoid/deathrun#5]
I realize this is a older mod. In my opinion one of the best made but unfortunately since gmod updated I am getting script errors on setting player class. If you have any idea why I would appreciate it.

**Comment by BlackVoid** [comment]
Should be fixed, however since I'm not playing Garrysmod nor the gamemode anymore not a lot of testing was done.

**Comment by Stinggy** [comment]
Thank you very much. I will try it later tonight. Really appreciate it.
