### ISSUE TITLE
Still getting SetPlayerclass script errors.

### ISSUE THREAD

**Issue by Stinggy** [BlackVoid/deathrun#8]
this is the errors I get after your newest changes.

`Couldn't include file 'classes\death.lua' (File not found) (@gamemodes/deathrun/gamemode/cl_init.lua (line 11))
Couldn't include file 'classes\runner.lua' (File not found) (@gamemodes/deathrun/gamemode/cl_init.lua (line 12))

SetPlayerClass - attempt to use unknown player class runner!`

I think gmod made some changes to the setplayerclass the way it works.

**Comment by BlackVoid** [comment]
Should be fixed now, forgot to add those files to be downloaded by the client, since I tried it without a dedicated server it was not required to work, if it's still not fixed comment in the ticket instead of opening a new one.

**Comment by Stinggy** [comment]
Do I still leave the changes in cl_i it.lua

**Comment by Stinggy** [comment]
Do I still leave the last changes In the cl_init.lua

**Comment by BlackVoid** [comment]
Yes, you take all the changes I've made. Just pull the latest version.

**Comment by Stinggy** [comment]
Seems to be working now other than I'm not sure what's supposed to be on the bottom right of the HUD it's not really indicating anything

**Comment by Stinggy** [comment]
Nevermind I figured out that displays amno lol. Thanks again works great!
